### ISSUE TITLE
Branch access rights

### ISSUE THREAD

**Issue by jfparisi** [pabloprf/MITIM-fusion#5]
Running my own local branch on a PPPL cluster but I don't have access rights to push this branch (not to main, but to my own branch). Is this something you would be willing to allow?

**Comment by pabloprf** [comment]
Added you as collaborator, that should fix the issue.

**Comment by jfparisi** [comment]
Thanks. Still encountering the same issue. My git username is jfparisi. Possibly an issue on my end, I’ll troubleshoot more.

-bash-4.2$ git push --set-upstream origin pppl_spark
ERROR: Permission to pabloprf/MITIM-fusion.git denied to jfparisi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pabloprf** [comment]
I think it's because you have to accept the invite first. It says "pending" to me

**Comment by jfparisi** [comment]
My bad, all working now. Thanks!
